export const SARC_INFO = {
  title: "SARC-F",
  subtitle: "Resultados para la detección de sarcopenia",
  questions: [
    "¿Qué tanta dificultad tiene para llevar o cargar 4.5 kg?",
    "¿Qué tanta dificultad tiene para cruzar caminando por un cuarto?",
    "¿Qué tanta dificultad tiene para levantarse de una silla o cama?",
    "¿Qué tanta dificultad tiene para subir 10 escalones?",
    "¿Cuántas veces se ha caído en el último año?",
  ],
  responses: [
    ["Ninguna", "Alguna", "Mucha o incapaz"],
    ["Ninguna", "Alguna", "Mucha, usando auxiliares o incapaz"],
    ["Ninguna", "Alguna", "Mucha o incapaz sin ayuda"],
    ["Ninguna", "Alguna", "Mucha o incapaz"],
    ["Ninguna", "1-3 caídas", "4 o más caídas"],
  ],
};

export const GDS15_INFO = {
  title: "Geriatric Depression Scale (GDS-15)",
  subtitle: "Escala Geriátrica de Depresión de 15 ítems",
  questions: [
    "¿En general, está satisfecho(a) con su vida?",
    "¿Ha abandonado muchas de sus tareas habituales y aficiones?",
    "¿Siente que su vida está vacía?",
    "¿Se siente con frecuencia aburrido(a)?",
    "¿Se encuentra de buen humor la mayor parte del tiempo?",
    "¿Teme que algo malo pueda ocurrirle?",
    "¿Se siente feliz la mayor parte del tiempo?",
    "¿Con frecuencia se siente desamparado(a), desprotegido(a)?",
    "¿Prefiere usted quedarse en casa, más que salir y hacer cosas nuevas?",
    "¿Cree que tiene más problemas de memoria que la mayoría de la gente?",
    "¿En estos momentos, piensa que es estupendo estar vivo(a)?",
    "¿Actualmente se siente un(a) inútil?",
    "¿Se siente lleno(a) de energía?",
    "¿Se siente sin esperanza en este momento?",
    "¿Piensa que la mayoría de la gente está en mejor situación que usted?",
  ],
  responses: [
    ["Sí", "No"],
    ["Sí", "No"],
    ["Sí", "No"],
    ["Sí", "No"],
    ["Sí", "No"],
    ["Sí", "No"],
    ["Sí", "No"],
    ["Sí", "No"],
    ["Sí", "No"],
    ["Sí", "No"],
    ["Sí", "No"],
    ["Sí", "No"],
    ["Sí", "No"],
    ["Sí", "No"],
    ["Sí", "No"],
  ],
};

export const CESD7_INFO = {
  title: "Escala de Depresión del Centro de Estudios Epidemiológicos (CESD-7)",
  subtitle: "Durante la última semana usted...",
  questions: [
    "¿Sentía como si no pudiera quitarse la tristeza?",
    "¿Le costaba concentrarse en lo que estaba haciendo?",
    "¿Se sintió deprimido/a?",
    "¿Le parecía que todo lo que hacía era un esfuerzo?",
    "¿No durmió bien?",
    "¿Disfrutó de la vida?",
    "¿Se sintió triste?",
  ],
  responses: [
    [
      "Rara vez o nunca (menos de 1 día)",
      "Pocas veces o alguna vez (1-2 días)",
      "Un número de veces considerable (3-4 días)",
      "Todo el tiempo o la mayoría del tiempo (5-7 días)",
    ],
    [
      "Rara vez o nunca (menos de 1 día)",
      "Pocas veces o alguna vez (1-2 días)",
      "Un número de veces considerable (3-4 días)",
      "Todo el tiempo o la mayoría del tiempo (5-7 días)",
    ],
    [
      "Rara vez o nunca (menos de 1 día)",
      "Pocas veces o alguna vez (1-2 días)",
      "Un número de veces considerable (3-4 días)",
      "Todo el tiempo o la mayoría del tiempo (5-7 días)",
    ],
    [
      "Rara vez o nunca (menos de 1 día)",
      "Pocas veces o alguna vez (1-2 días)",
      "Un número de veces considerable (3-4 días)",
      "Todo el tiempo o la mayoría del tiempo (5-7 días)",
    ],
    [
      "Rara vez o nunca (menos de 1 día)",
      "Pocas veces o alguna vez (1-2 días)",
      "Un número de veces considerable (3-4 días)",
      "Todo el tiempo o la mayoría del tiempo (5-7 días)",
    ],
    [
      "Todo el tiempo o la mayoría del tiempo (5-7 días)",
      "Un número de veces considerable (3-4 días)",
      "Pocas veces o alguna vez (1-2 días)",
      "Rara vez o nunca (menos de 1 día)",
    ],
    [
      "Rara vez o nunca (menos de 1 día)",
      "Pocas veces o alguna vez (1-2 días)",
      "Un número de veces considerable (3-4 días)",
      "Todo el tiempo o la mayoría del tiempo (5-7 días)",
    ],
  ],
};

export const FRAIL_INFO = {
  title: "Escala FRAIL",
  subtitle: "Evaluación de fragilidad en adultos mayores",
  questions: [
    "En las últimas 4 semanas, ¿Qué tanto tiempo se sintió fatigado/a?",
    "¿Tiene dificultad para subir 10 escalones (una escalera)?",
    "¿Tiene dificultad para caminar 100 metros (dos cuadras sin descansar)?",
    "¿Tiene hipertensión arterial sistémica?",
    "¿Tiene diabetes?",
    "¿Tiene cáncer (otro que no sea un cáncer menor en piel)?",
    "¿Tiene enfermedad pulmonar crónica?",
    "¿Tiene cardiopatía isquémica?",
    "¿Tiene insuficiencia cardíaca congestiva?",
    "¿Tiene angina?",
    "¿Tiene asma?",
    "¿Tiene artritis (incluyendo osteoartrosis y artritis reumatoide)?",
    "¿Tiene enfermedad vascular cerebral (embolia)?",
    "¿Tiene enfermedad renal crónica?",
    "Peso actual (kg)",
    "Peso hace un año (kg)",
  ],
  responses: [
    [
      "Todo el tiempo",
      "La mayor parte del tiempo",
      "Algo de tiempo",
      "Muy poco tiempo",
      "Nada de tiempo",
    ],
    ["Sí", "No"],
    ["Sí", "No"],
    ["Sí", "No"],
    ["Sí", "No"],
    ["Sí", "No"],
    ["Sí", "No"],
    ["Sí", "No"],
    ["Sí", "No"],
    ["Sí", "No"],
    ["Sí", "No"],
    ["Sí", "No"],
    ["Sí", "No"],
    ["Sí", "No"],
    [], // Campo numérico
    [], // Campo numérico
  ],
};

export const BRADEN_INFO = {
  title: "Escala de Braden",
  subtitle: "Valoración del riesgo de úlceras por presión",
  questions: [
    "Percepción Sensorial",
    "Exposición a la Humedad",
    "Actividad",
    "Movilidad",
    "Nutrición",
    "Roce y Peligro de Lesiones",
  ],
  responses: [
    [
      "Completamente limitada",
      "Muy limitada",
      "Ligeramente limitada",
      "Sin limitaciones",
    ],
    [
      "Constantemente húmeda",
      "A menudo húmeda",
      "Ocasionalmente húmeda",
      "Raramente húmeda",
    ],
    [
      "Encamado/a",
      "En silla",
      "Deambula ocasionalmente",
      "Deambula frecuentemente",
    ],
    [
      "Completamente inmóvil",
      "Muy limitada",
      "Ligeramente limitada",
      "Sin limitaciones",
    ],
    ["Muy pobre", "Probablemente inadecuada", "Adecuada", "Excelente"],
    ["Problema", "Problema potencial", "Sin problema aparente"],
  ],
};

export const NORTON_INFO = {
  title: "Escala de Norton",
  subtitle: "Resultados para el riesgo de úlceras por presión",
  questions: [
    "Estado físico",
    "Estado mental",
    "Actividad",
    "Movilidad",
    "Incontinencia",
  ],
  responses: [
    ["Muy mala", "Malo", "Débil", "Bueno"],
    ["Estuporoso", "Confuso", "Apático", "Alerta"],
    ["En cama", "En silla de ruedas", "Camina con ayuda", "Camina"],
    ["Inmovil", "Muy limitada", "Limitada ligeramente", "Completa"],
    ["Doble incontinencia", "Usualmente uriniaria", "Ocasional", "No hay"],
  ],
};

export const MNA_INFO = {
  title: "Mini-Nutritional Assessment-Short Form (MNA-SF)",
  subtitle: "Resultados para la mini evaluación nutricional",
  questions: [
    "Ha perdido el apetito? Ha comido menos por falta de apetito, problemas digestivos, dificultades de masticación o deglución en los últimos 3 meses?",
    "Pérdida reciente de peso (< 3 meses)",
    "Movilidad",
    "Ha tenido una enfermedad aguda o situación de estrés psicológico en los últimos 3 meses",
    "Problemas neuropsicológicos",
    "Índice de masa corporal (IMC)",
    "Perímetro de la pantorrilla (cm)",
  ],
  responses: [
    ["Ha comido mucho menos", "Ha comido menos", "Ha comido igual"],
    [
      "Pérdida de peso > 3 kg",
      "No lo sabe",
      "Pérdida de peso entre 1 y 3 kg",
      "No ha habido pérdida de peso",
    ],
    ["De la cama al sillón", "Autonomía en el interior", "Sale del domicilio"],
    ["Sí", "No"],
    [
      "Demencia o depresión grave",
      "Demencia moderada",
      "Sin problemas psicológicos",
    ],
    [
      "IMC < 19 kg/m²",
      "IMC entre 19 y 21 kg/m²",
      "IMC entre 21 y 23 kg/m²",
      "IMC ≥ 23 kg/m²",
    ],
    ["< 31 cm", "≥ 31 cm"],
  ],
};

export const BARRERAS_INFO = {
  title: "Evaluación de Barreras",
  subtitle: "Resultados para la evaluación de barreras en adultos mayores",
  questions: [
    "¿En su hogar existe el espacio suficiente para permitir su libre movimiento?",
    "De acuerdo a su condición de salud, ¿Su vivienda está adaptada para una persona mayor, (superficies lisas, pasillos lo suficientemente anchos para su silla de ruedas, cocina diseñada de manera acorde)?",
    "¿Considera que su vivienda es la idónea de acuerdo a su condición de salud?",
    "¿El equipamiento para modificar su vivienda está disponible?",
    "¿Está usted en posibilidades de cambiar a una vivienda mejor adaptada de acuerdo a su condición de salud?",
    "Cuando usted sale del hogar, ¿Considera que puede realizar su traslado sin problemas?",
    "¿El camino para los peatones está libre de obstrucciones?",
    "¿En su comunidad, las aceras presentan un correcto mantenimiento?",
    "En su comunidad, ¿Las aceras están libres de obstrucciones (por ejemplo, vendedores ambulantes, vehículos estacionados, árboles)?",
    "¿Usted considera que las normas y reglas de tránsito se respetan?",
    "¿Los edificios públicos que usted visita son accesibles?",
    "¿Usted realiza actividad física en la comunidad y/o en el hogar?",
    "¿Usted se encuentra interesado en realizar actividad física?",
    "¿Considera que su situación de salud le permite realizar actividad física?",
    "¿En su comunidad se promueve la actividad física?",
    "¿Considera que las instalaciones para hacer actividad física en su comunidad toman en cuenta las preferencias o necesidades de las personas mayores?",
    "¿Considera que su comunidad es segura para realizar actividad física?",
    "¿Considera que el flujo vehicular en su colonia le permite realizar actividad física?",
    "¿Tiene usted el tiempo para realizar actividad física?",
    "¿Sabe usted cómo iniciar un programa seguro de actividad física en casa?",
    "¿En su lugar de trabajo se promueve la actividad física?",
    "¿Usted realiza actividad física en su trabajo?",
    "Cuando usted ha acudido a consulta, ¿Le han prescrito realizar actividad física?",
    "¿Conoce usted los lugares de encuentro que incluyan a personas mayores en su comunidad (centros recreativos, escuelas, bibliotecas, centros comunitarios, parques o jardines)?",
    "¿Los sectores público y privado realizan actividades de participación para adultos mayores en su comunidad?",
    "¿Usted participa en actividades comunitarias: (recreación, actividades físicas, sociales o espirituales)?",
    "¿Considera que la ubicación es conveniente para usted?",
    "¿Considera que el horario es conveniente?",
    "¿La admisión para participar es abierta?",
    "¿El precio para participar constituye algún problema para usted?",
    "¿Conoce usted la gama de actividades que puede realizar en su comunidad?",
    "¿Tiene interés en llevarlas a cabo?",
    "¿Considera usted que las actividades alientan/estimulan la participación de personas de diferentes edades?",
    "¿Las instalaciones de dichos lugares de encuentro promueven el uso compartido para personas de distintas edades?",
    "¿Los lugares de encuentro y las actividades locales promueven el acercamiento e intercambio entre los vecinos?",
    "¿El transporte público es accesible en cuanto a precio?",
    "¿Considera que el transporte público es confiable y frecuente?",
    "¿Considera que las rutas de transportes son adecuadas de acuerdo a sus necesidades?",
    "De acuerdo a su condición de salud, ¿considera que los vehículos son accesibles?",
    "¿Considera que las paradas del transporte son adecuadas?",
    "¿Considera usted que la actitud del conductor al manejar es la correcta?",
    "¿Considera usted que los caminos en su comunidad presentan buen estado de conservación?",
    "¿Le han prescrito dispositivos auxiliares o ayudas técnicas?",
    "¿Usted considera que requiere de algo?",
    "¿Dispone de ello?",
    "¿Se los han ofrecido de manera gratuita en alguna dependencia del gobierno?",
    "¿Ha acudido a algún otro lugar para que le apoyen con ello?",
  ],
  responses: Array(47).fill(["Si", "No"]),
};

export const MALTRATO_INFO = {
  title: "Evaluación de Maltrato",
  subtitle: "Resultados para la detección de maltrato en adultos mayores",
  questions: [
    "¿Le han golpeado?",
    "¿Le han dado puñetazos o patadas?",
    "¿Le han empujado o le han jalado el pelo?",
    "¿Le han aventado algún objeto?",
    "¿Le han agredido con algún cuchillo o navaja?",
    "¿Le han humillado o se han burlado de usted?",
    "¿Le han tratado con indiferencia o le han ignorado?",
    "¿Le han aislado o le han corrido de la casa?",
    "¿Le han hecho sentir miedo?",
    "¿No han respetado sus decisiones?",
    "¿Le han prohibido salir o que la visiten?",
    "¿Le han dejado de proporcionar la ropa, el calzado, etc?",
    "¿Le han dejado de suministrar los medicamentos que necesita?",
    "¿Le han negado protección cuando la necesita?",
    "¿Le han negado acceso a la casa que habita?",
    "¿Alguien ha manejado o maneja su dinero sin su consentimiento?",
    "¿Le han quitado su dinero?",
    "¿Le han tomado sin permiso algún bien de su propiedad?",
    "¿Le han vendido alguna propiedad de su pertenencia sin su consentimiento?",
    "¿Le han presionado para que deje de usar usted el propietario de su casa o de alguna otra propiedad?",
    "¿Le han exigido tener relaciones sexuales aunque usted no quiera?",
    "¿Le han tocado sus genitales sin su consentimiento?",
  ],
  responses: Array(22).fill(["No", "Si"]),
};

export const OARS_INFO = {
  title: "Older American and Resource Socials (OARS)",
  subtitle: "Escala de recursos sociales - Formulario informativo",
  questions: [
    "¿Su estado civil es?",
    "¿Vive su esposo(a)?",
    "¿Con quién vive usted?",
    "¿Con cuántas personas vive?",
    "¿En el último año, cuántas veces visitó a su familia, amigos, durante los fines de semana o las vacaciones?",
    "¿A cuántas personas conoce lo suficientemente bien como para visitarles en casa?",
    "¿En la última semana, cuántas veces habló por teléfono con amigos, familiares u otros?",
    "¿Cuántas veces en la última semana pasó algún tiempo con alguien que no vive con usted?",
    "¿Tiene alguien en quién confiar?",
    "¿Se encuentra solo(a) o se siente en soledad a menudo, a veces o casi nunca?",
    "¿Ve a sus familiares y amigos a menudo como quisiera?",
    "¿Si alguna vez necesitase ayuda por encontrarse enfermo(a) o incapacitado(a) ¿Tendría quién le prestase ayuda?",
    "¿Esa persona cuidaría de usted?",
    "¿Quién sería esa persona? - Nombre:",
    "¿Quién sería esa persona? - Relación:",
    "¿Cómo considera la convivencia y apoyo de familiares y amigos?",
  ],
  responses: [
    [
      "Soltero (a)",
      "Casado (a) o Unión Libre",
      "Viudo (a)",
      "Divorciado (a)",
      "Separado (a)",
    ],
    ["No", "Sí"],
    [
      "Nadie",
      "Esposo (a)",
      "Hijos (as)",
      "Nietos (as)",
      "Padres",
      "Hermanos (as)",
      "Otros familiares",
      "Amigos (as)",
      "Cuidadores pagados",
      "Otros",
    ],
    [], // Campo numérico
    [
      "Nunca",
      "Cada seis meses",
      "Cada tres meses",
      "Cada mes",
      "Menos de una vez al mes",
      "Menos de una vez a la semana",
      "1 – 3 veces a la semana",
      "Más de cuatro veces a la semana",
    ],
    ["Ninguna", "Una o dos", "De tres a cuatro", "Cinco o más"],
    [
      "Ninguna vez",
      "Una vez a la semana",
      "Dos a seis veces a la semana",
      "Más de seis veces a la semana",
      "Una vez al día",
    ],
    [
      "Ninguna vez",
      "Una vez",
      "2 – 6 veces al día",
      "Más de seis veces al día",
    ],
    ["No", "Sí"],
    ["Casi nunca", "Algunas veces", "A menudo"],
    ["Algo triste por la poca frecuencia", "Tan a menudo como quisiera"],
    ["No", "Sí"],
    [
      "Sólo de forma pasajera",
      "Durante un corto período de tiempo",
      "De forma indefinida",
    ],
    [], // Campo de texto
    [], // Campo de texto
    [
      "Muy insatisfactoria",
      "Insatisfactoria",
      "Muy satisfactoria",
      "Satisfactoria",
    ],
  ],
};
