export const SARC_INFO = {
  title: "SARC-F",
  subtitle: "Resultados para la detección de sarcopenia",
  questions: [
    "¿Qué tanta dificultad tiene para llevar o cargar 4.5 kg?",
    "¿Qué tanta dificultad tiene para cruzar caminando por un cuarto?",
    "¿Qué tanta dificultad tiene para levantarse de una silla o cama?",
    "¿Qué tanta dificultad tiene para subir 10 escalones?",
    "¿Cuántas veces se ha caído en el último año?",
  ],
  responses: [
    ["Ninguna", "Alguna", "Mucha o incapaz"],
    ["Ninguna", "Alguna", "Mucha, usando auxiliares o incapaz"],
    ["Ninguna", "Alguna", "Mucha o incapaz sin ayuda"],
    ["Ninguna", "Alguna", "Mucha o incapaz"],
    ["Ninguna", "1-3 caídas", "4 o más caídas"],
  ],
};

export const NORTON_INFO = {
  title: "Escala de Norton",
  subtitle: "Resultados para el riesgo de úlceras por presión",
  questions: [
    "Estado físico",
    "Estado mental",
    "Actividad",
    "Movilidad",
    "Incontinencia",
  ],
  responses: [
    ["Muy mala", "Malo", "Débil", "Bueno"],
    ["Estuporoso", "Confuso", "Apático", "Alerta"],
    ["En cama", "En silla de ruedas", "Camina con ayuda", "Camina"],
    ["Inmovil", "Muy limitada", "Limitada ligeramente", "Completa"],
    ["Doble incontinencia", "Usualmente uriniaria", "Ocasional", "No hay"],
  ],
};

export const MNA_INFO = {
  title: "Mini-Nutritional Assessment-Short Form (MNA-SF)",
  subtitle: "Resultados para la mini evaluación nutricional",
  questions: [
    "Ha perdido el apetito? Ha comido menos por falta de apetito, problemas digestivos, dificultades de masticación o deglución en los últimos 3 meses?",
    "Pérdida reciente de peso (< 3 meses)",
    "Movilidad",
    "Ha tenido una enfermedad aguda o situación de estrés psicológico en los últimos 3 meses",
    "Problemas neuropsicológicos",
    "Índice de masa corporal (IMC)",
    "Perímetro de la pantorrilla (cm)",
  ],
  responses: [
    ["Ha comido mucho menos", "Ha comido menos", "Ha comido igual"],
    [
      "Pérdida de peso > 3 kg",
      "No lo sabe",
      "Pérdida de peso entre 1 y 3 kg",
      "No ha habido pérdida de peso",
    ],
    ["De la cama al sillón", "Autonomía en el interior", "Sale del domicilio"],
    ["Sí", "No"],
    [
      "Demencia o depresión grave",
      "Demencia moderada",
      "Sin problemas psicológicos",
    ],
    [
      "IMC < 19 kg/m²",
      "IMC entre 19 y 21 kg/m²",
      "IMC entre 21 y 23 kg/m²",
      "IMC ≥ 23 kg/m²",
    ],
    ["< 31 cm", "≥ 31 cm"],
  ],
};

export const BARRERAS_INFO = {
  title: "Evaluación de Barreras",
  subtitle: "Resultados para la evaluación de barreras en adultos mayores",
  questions: [
    "¿En su hogar existe el espacio suficiente para permitir su libre movimiento?",
    "De acuerdo a su condición de salud, ¿Su vivienda está adaptada para una persona mayor, (superficies lisas, pasillos lo suficientemente anchos para su silla de ruedas, cocina diseñada de manera acorde)?",
    "¿Considera que su vivienda es la idónea de acuerdo a su condición de salud?",
    "¿El equipamiento para modificar su vivienda está disponible?",
    "¿Está usted en posibilidades de cambiar a una vivienda mejor adaptada de acuerdo a su condición de salud?",
    "Cuando usted sale del hogar, ¿Considera que puede realizar su traslado sin problemas?",
    "¿El camino para los peatones está libre de obstrucciones?",
    "¿En su comunidad, las aceras presentan un correcto mantenimiento?",
    "En su comunidad, ¿Las aceras están libres de obstrucciones (por ejemplo, vendedores ambulantes, vehículos estacionados, árboles)?",
    "¿Usted considera que las normas y reglas de tránsito se respetan?",
    "¿Los edificios públicos que usted visita son accesibles?",
    "¿Usted realiza actividad física en la comunidad y/o en el hogar?",
    "¿Usted se encuentra interesado en realizar actividad física?",
    "¿Considera que su situación de salud le permite realizar actividad física?",
    "¿En su comunidad se promueve la actividad física?",
    "¿Considera que las instalaciones para hacer actividad física en su comunidad toman en cuenta las preferencias o necesidades de las personas mayores?",
    "¿Considera que su comunidad es segura para realizar actividad física?",
    "¿Considera que el flujo vehicular en su colonia le permite realizar actividad física?",
    "¿Tiene usted el tiempo para realizar actividad física?",
    "¿Sabe usted cómo iniciar un programa seguro de actividad física en casa?",
    "¿En su lugar de trabajo se promueve la actividad física?",
    "¿Usted realiza actividad física en su trabajo?",
    "Cuando usted ha acudido a consulta, ¿Le han prescrito realizar actividad física?",
    "¿Conoce usted los lugares de encuentro que incluyan a personas mayores en su comunidad (centros recreativos, escuelas, bibliotecas, centros comunitarios, parques o jardines)?",
    "¿Los sectores público y privado realizan actividades de participación para adultos mayores en su comunidad?",
    "¿Usted participa en actividades comunitarias: (recreación, actividades físicas, sociales o espirituales)?",
    "¿Considera que la ubicación es conveniente para usted?",
    "¿Considera que el horario es conveniente?",
    "¿La admisión para participar es abierta?",
    "¿El precio para participar constituye algún problema para usted?",
    "¿Conoce usted la gama de actividades que puede realizar en su comunidad?",
    "¿Tiene interés en llevarlas a cabo?",
    "¿Considera usted que las actividades alientan/estimulan la participación de personas de diferentes edades?",
    "¿Las instalaciones de dichos lugares de encuentro promueven el uso compartido para personas de distintas edades?",
    "¿Los lugares de encuentro y las actividades locales promueven el acercamiento e intercambio entre los vecinos?",
    "¿El transporte público es accesible en cuanto a precio?",
    "¿Considera que el transporte público es confiable y frecuente?",
    "¿Considera que las rutas de transportes son adecuadas de acuerdo a sus necesidades?",
    "De acuerdo a su condición de salud, ¿considera que los vehículos son accesibles?",
    "¿Considera que las paradas del transporte son adecuadas?",
    "¿Considera usted que la actitud del conductor al manejar es la correcta?",
    "¿Considera usted que los caminos en su comunidad presentan buen estado de conservación?",
    "¿Le han prescrito dispositivos auxiliares o ayudas técnicas?",
    "¿Usted considera que requiere de algo?",
    "¿Dispone de ello?",
    "¿Se los han ofrecido de manera gratuita en alguna dependencia del gobierno?",
    "¿Ha acudido a algún otro lugar para que le apoyen con ello?",
  ],
  responses: Array(47).fill(["Si", "No"]),
};
